import { iconePadrao } from "./icones";

const TEMA_PADRAO = {
  fundo: "#0b0b10",
  texto: "#f4f4f5",
  destaque: "#155eff",
  fonte: "sans",
  alinhamento: "centro",
  largura: "media",
};

const IMG_S3 = (arquivo) =>
  `https://singlepage-bucket-images.s3.us-east-1.amazonaws.com/templates/${arquivo}`;

function botaoPadrao(extras = {}) {
  return {
    rotulo: "Meu link",
    url: "https://",
    estilo: "preenchido",
    novaAba: true,
    hoverFundo: "",
    hoverCor: "",
    hoverEscala: 1.04,
    hoverSombra: true,
    ...extras,
  };
}

function bloco(tipo, props) {
  return { id: crypto.randomUUID(), tipo, props };
}

function tema(extra) {
  return { ...TEMA_PADRAO, ...extra };
}

function icones(itens) {
  return bloco("icones", { itens: itens.map((item) => iconePadrao(item)) });
}

function botoes(itens) {
  return bloco("botoes", { itens: itens.map((item) => botaoPadrao(item)) });
}

function form(extra = {}) {
  return bloco("formulario", {
    destEmail: "oi@email.com",
    assunto: "Mensagem pelo site",
    placeholder: "seu@email.com",
    botao: "Enviar",
    mostrarNome: true,
    mostrarMensagem: true,
    ...extra,
  });
}

function galeria(arquivos = ["portfolio-1.jpg", "portfolio-2.jpg", "portfolio-3.jpg", "portfolio-4.jpg"]) {
  return bloco("galeria", { urls: arquivos.map(IMG_S3) });
}

function layout({ id, nome, descricao, categoria, tom, capa, tema: temaPagina, blocos }) {
  return {
    id,
    nome,
    descricao,
    categoria,
    tom,
    capa,
    destaque: false,
    tema: temaPagina,
    blocos,
  };
}

const PERFIL = [
  layout({
    id: "perfil-criativo",
    nome: "Mel Rivera",
    descricao: "Ilustração, cartaz e um retrato que parece capa.",
    categoria: "perfil",
    tom: "criativo",
    capa: IMG_S3("perfil.jpg"),
    tema: tema({ fundo: "#1b0633", texto: "#ffe8ff", destaque: "#ff2bd6", fonte: "serif", alinhamento: "esquerda", largura: "media" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Mel Rivera",
        subtitulo: "Ilustro capas, cartazes e um pouco de caos organizado.",
        fotoUrl: IMG_S3("perfil.jpg"),
        cta: "Encomendar um desenho",
        url: "mailto:mel@email.com",
        estiloBotao: "preenchido",
      }),
      icones([
        { nome: "Palette", url: "https://", fundo: "#ff2bd6", animacao: "pulso" },
        { nome: "Instagram", url: "https://instagram.com", fundo: "#5b21b6", animacao: "flutuar" },
        { nome: "Mail", url: "mailto:mel@email.com", fundo: "#1d1d1f", animacao: "nenhuma" },
      ]),
      bloco("texto", { titulo: "Agora", corpo: "Abrindo agenda para 3 projetos de capa. O resto do ano é livro e risografia." }),
    ],
  }),
  layout({
    id: "perfil-colorido",
    nome: "Bia Sol",
    descricao: "Cerâmica, cor e mesa posta.",
    categoria: "perfil",
    tom: "colorido",
    capa: IMG_S3("perfil.jpg"),
    tema: tema({ fundo: "#ffe600", texto: "#111111", destaque: "#5b21ff", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Bia Sol",
        subtitulo: "Cerâmica, cor e mesa posta. Tudo que cabe num prato.",
        fotoUrl: IMG_S3("perfil.jpg"),
        cta: "Pedir um conjunto",
        url: "mailto:bia@email.com",
        estiloBotao: "preenchido",
      }),
      icones([
        { nome: "Instagram", url: "https://instagram.com", fundo: "#ff006e", animacao: "pular" },
        { nome: "ShoppingBag", url: "https://", fundo: "#5b21ff", animacao: "pulso" },
        { nome: "Mail", url: "mailto:bia@email.com", fundo: "#111111", animacao: "nenhuma" },
      ]),
      bloco("texto", { titulo: "Forno aberto", corpo: "Peças únicas aos sábados. Encomenda personalizada com 20 dias." }),
    ],
  }),
  layout({
    id: "perfil-sobrio",
    nome: "Clara Mendes",
    descricao: "Interiores. Casas quietas, luz certa.",
    categoria: "perfil",
    tom: "sobrio",
    capa: IMG_S3("perfil.jpg"),
    tema: tema({ fundo: "#ebe6dc", texto: "#2f2b26", destaque: "#6f675e", fonte: "serif", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Clara Mendes",
        subtitulo: "Arquitetura de interiores. Casas quietas, luz certa.",
        fotoUrl: IMG_S3("perfil.jpg"),
        cta: "Agendar conversa",
        url: "mailto:clara@email.com",
        estiloBotao: "contorno",
      }),
      bloco("texto", { titulo: "", corpo: "Atendo projetos residenciais em São Paulo. Uma obra por vez." }),
    ],
  }),
  layout({
    id: "perfil-serio",
    nome: "Henrique Vale",
    descricao: "Conselho e estratégia para empresa familiar.",
    categoria: "perfil",
    tom: "serio",
    capa: IMG_S3("perfil.jpg"),
    tema: tema({ fundo: "#0b1220", texto: "#e8e6e1", destaque: "#c5a572", alinhamento: "esquerda", largura: "media" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Henrique Vale",
        subtitulo: "Estratégia para empresas familiares. Conselho, sucessão e clareza.",
        fotoUrl: "",
        cta: "Solicitar briefing",
        url: "mailto:henrique@email.com",
        estiloBotao: "contorno",
      }),
      bloco("texto", {
        titulo: "Atuação",
        corpo: "20 anos entre operação e conselho. Trabalho com times pequenos e decisões grandes.",
      }),
      icones([
        { nome: "Linkedin", url: "https://linkedin.com", fundo: "#1d2a44", animacao: "nenhuma" },
        { nome: "Mail", url: "mailto:henrique@email.com", fundo: "#c5a572", cor: "#0b1220", animacao: "nenhuma" },
      ]),
    ],
  }),
  layout({
    id: "perfil-minimalista",
    nome: "N. Kato",
    descricao: "Fotografia. Nome, uma linha, um e-mail.",
    categoria: "perfil",
    tom: "minimalista",
    capa: "",
    tema: tema({ fundo: "#ffffff", texto: "#111111", destaque: "#111111", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "N. Kato",
        subtitulo: "Fotografia.",
        fotoUrl: "",
        cta: "oi@kato.com",
        url: "mailto:oi@kato.com",
        estiloBotao: "texto",
      }),
    ],
  }),
  layout({
    id: "perfil-maximalista",
    nome: "Kika Torres",
    descricao: "Direção, styling e uma página que não para quieta.",
    categoria: "perfil",
    tom: "maximalista",
    capa: IMG_S3("perfil.jpg"),
    tema: tema({ fundo: "#0b0b10", texto: "#fafafa", destaque: "#ff3b00", largura: "larga" }),
    blocos: () => [
      bloco("navegacao", { itens: [{ rotulo: "Eu", ancora: "eu" }, { rotulo: "Trabalho", ancora: "trabalho" }, { rotulo: "Fala", ancora: "fala" }] }),
      bloco("secao", { ancora: "eu", titulo: "", subtitulo: "" }),
      bloco("capa", {
        titulo: "Kika Torres",
        subtitulo: "Direção, styling, um pouco de palco e muito recado no stories.",
        fotoUrl: IMG_S3("perfil.jpg"),
        cta: "Me chama",
        url: "#fala",
        estiloBotao: "preenchido",
        novaAba: false,
      }),
      icones([
        { nome: "Instagram", url: "https://instagram.com", fundo: "#ff3b00", animacao: "pular" },
        { nome: "Youtube", url: "https://youtube.com", fundo: "#155eff", animacao: "pulso" },
        { nome: "Music", url: "https://spotify.com", fundo: "#b8ff00", cor: "#111", animacao: "flutuar" },
        { nome: "Mail", url: "mailto:kika@email.com", fundo: "#7c3aed", animacao: "pulso" },
      ]),
      bloco("secao", { ancora: "trabalho", titulo: "Em cena", subtitulo: "Últimos frames." }),
      galeria(),
      bloco("texto", { titulo: "Agenda aberta", corpo: "Campanha, editorial e evento. Manda referência e prazo — eu devolvo no mesmo dia." }),
      botoes([
        { rotulo: "Lookbook", url: "https://", estilo: "preenchido" },
        { rotulo: "Imprensa", url: "https://", estilo: "contorno" },
        { rotulo: "Contrato", url: "mailto:kika@email.com", estilo: "texto" },
      ]),
      bloco("secao", { ancora: "fala", titulo: "Fala comigo", subtitulo: "" }),
      form({ titulo: "", destEmail: "kika@email.com", assunto: "Oi, Kika", botao: "Mandar recado" }),
      bloco("rodape", { texto: "© Kika Torres — tudo ao mesmo tempo" }),
    ],
  }),
];

const LANDING = [
  layout({
    id: "landing-criativa",
    nome: "O caderno",
    descricao: "Uma página por dia. Sem streak, sem ranking.",
    categoria: "landing",
    tom: "criativo",
    capa: IMG_S3("landing.jpg"),
    tema: tema({ fundo: "#fff4d6", texto: "#1a0533", destaque: "#6d28ff", fonte: "serif", largura: "media" }),
    blocos: () => [
      bloco("imagem", { url: IMG_S3("landing.jpg"), alt: "Produto", caption: "" }),
      bloco("capa", {
        titulo: "O caderno que não te cobra produtividade",
        subtitulo: "Uma página por dia. Sem streak, sem ranking, sem vergonha.",
        fotoUrl: "",
        cta: "Quero o primeiro caderno",
        url: "#formulario",
        estiloBotao: "preenchido",
        novaAba: false,
      }),
      bloco("texto", { titulo: "A tese", corpo: "Ferramenta demais vira segundo emprego. Aqui cabe só o que você ainda lembra à noite." }),
      form({ titulo: "Lista de espera", assunto: "Caderno", botao: "Me avisa", mostrarMensagem: false }),
    ],
  }),
  layout({
    id: "landing-colorida",
    nome: "POP lista",
    descricao: "A lista do dia em 12 segundos.",
    categoria: "landing",
    tom: "colorido",
    capa: IMG_S3("landing.jpg"),
    tema: tema({ fundo: "#3a0ca3", texto: "#fff7fb", destaque: "#ff006e", largura: "media" }),
    blocos: () => [
      bloco("capa", {
        titulo: "POP lista",
        subtitulo: "A lista do dia em 12 segundos. Cor, som e um check enorme.",
        fotoUrl: "",
        cta: "Entrar no beta",
        url: "#formulario",
        estiloBotao: "preenchido",
        novaAba: false,
      }),
      icones([
        { nome: "Zap", url: "", fundo: "#ff006e", animacao: "pulso" },
        { nome: "Sun", url: "", fundo: "#ffbe0b", cor: "#111", animacao: "girar" },
        { nome: "Music", url: "", fundo: "#00f5d4", cor: "#111", animacao: "pular" },
      ]),
      bloco("texto", { titulo: "Por que grita", corpo: "Porque a outra lista é cinza e você já esqueceu o que tinha nela." }),
      form({ titulo: "Quero o barulho", assunto: "Beta POP", botao: "Me coloca", mostrarMensagem: false }),
    ],
  }),
  layout({
    id: "landing-sobria",
    nome: "Caderno",
    descricao: "Tarefas do dia. Nada além.",
    categoria: "landing",
    tom: "sobrio",
    capa: IMG_S3("landing.jpg"),
    tema: tema({ fundo: "#d9d2c5", texto: "#2a2723", destaque: "#5c564c", fonte: "serif", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Caderno",
        subtitulo: "Tarefas do dia. Nada além.",
        fotoUrl: "",
        cta: "Pedir acesso",
        url: "#formulario",
        estiloBotao: "contorno",
        novaAba: false,
      }),
      bloco("texto", { titulo: "", corpo: "Sem conta social. Sem gráfico. Um dia, uma lista, um arquivo." }),
      form({ titulo: "", assunto: "Acesso Caderno", botao: "Escrever", mostrarNome: false, mostrarMensagem: false }),
    ],
  }),
  layout({
    id: "landing-seria",
    nome: "Ledger",
    descricao: "Caixa para sócios. Um número, um fechamento.",
    categoria: "landing",
    tom: "serio",
    capa: IMG_S3("landing.jpg"),
    tema: tema({ fundo: "#05070b", texto: "#f4f1ea", destaque: "#d4af37", alinhamento: "esquerda", largura: "media" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Ledger",
        subtitulo: "Controle de caixa para sócios. Um número, um responsável, um fechamento.",
        fotoUrl: "",
        cta: "Agendar demonstração",
        url: "#formulario",
        estiloBotao: "contorno",
        novaAba: false,
      }),
      bloco("texto", { titulo: "Para quem", corpo: "Empresas com 2 a 20 sócios que ainda fecham o mês em planilha compartilhada." }),
      bloco("texto", { titulo: "O que entra", corpo: "Saldo, previsão de 30 dias e um relatório que o conselho consegue ler." }),
      form({ titulo: "Demonstração", assunto: "Demo Ledger", botao: "Solicitar", mostrarMensagem: false }),
    ],
  }),
  layout({
    id: "landing-minimalista",
    nome: "Uma lista",
    descricao: "Uma frase e um campo de e-mail.",
    categoria: "landing",
    tom: "minimalista",
    capa: "",
    tema: tema({ fundo: "#fafafa", texto: "#171717", destaque: "#171717", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Uma lista.",
        subtitulo: "",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "texto",
      }),
      form({ titulo: "", assunto: "Lista", botao: "Quero", mostrarNome: false, mostrarMensagem: false }),
    ],
  }),
  layout({
    id: "landing-maximalista",
    nome: "App do dia",
    descricao: "Lista, calendário e um quadro para o time.",
    categoria: "landing",
    tom: "maximalista",
    capa: IMG_S3("landing.jpg"),
    tema: tema({ fundo: "#020617", texto: "#f8fafc", destaque: "#00e5ff", largura: "larga" }),
    blocos: () => [
      bloco("navegacao", { itens: [{ rotulo: "Produto", ancora: "produto" }, { rotulo: "Prova", ancora: "prova" }, { rotulo: "Lista", ancora: "formulario" }] }),
      bloco("secao", { ancora: "produto", titulo: "", subtitulo: "" }),
      bloco("imagem", { url: IMG_S3("landing.jpg"), alt: "Produto", caption: "" }),
      bloco("capa", {
        titulo: "O app que organiza o seu dia — e o do time",
        subtitulo: "Lista, calendário, lembrete e um quadro para quem trabalha junto.",
        fotoUrl: "",
        cta: "Entrar na lista",
        url: "#formulario",
        estiloBotao: "preenchido",
        novaAba: false,
      }),
      icones([
        { nome: "Check", url: "", fundo: "#00e5ff", cor: "#020617", animacao: "pulso" },
        { nome: "Calendar", url: "", fundo: "#155eff", animacao: "nenhuma" },
        { nome: "Users", url: "", fundo: "#b8ff00", cor: "#111", animacao: "flutuar" },
        { nome: "Bell", url: "", fundo: "#ff2d55", animacao: "pular" },
      ]),
      bloco("texto", { titulo: "O essencial", corpo: "Cadastre em 10 segundos. Veja o dia de relance. Aviso só no que importa." }),
      bloco("texto", { titulo: "Para o time", corpo: "Um quadro compartilhado. Sem 14 ferramentas. Sem reunião para alinhar a lista." }),
      bloco("texto", { titulo: "Para você", corpo: "Modo foco. Uma tarefa na tela. O resto espera." }),
      bloco("secao", { ancora: "prova", titulo: "Quem já usa", subtitulo: "" }),
      bloco("depoimentos", {
        itens: [
          { citacao: "Troquei três apps por este. O dia cabe numa tela.", autor: "Lia, estúdio" },
          { citacao: "O time parou de perguntar ‘cadê a lista?’.", autor: "Rafa, operação" },
        ],
      }),
      bloco("secao", { ancora: "formulario", titulo: "Lista de acesso", subtitulo: "Primeira leva em outubro." }),
      form({ titulo: "", assunto: "Quero o app", botao: "Quero acesso", mostrarMensagem: false }),
      botoes([
        { rotulo: "Twitter", url: "https://", estilo: "texto" },
        { rotulo: "Changelog", url: "https://", estilo: "texto" },
      ]),
      bloco("rodape", { texto: "© App do dia" }),
    ],
  }),
];

const FORMULARIO = [
  layout({
    id: "formulario-criativo",
    nome: "Briefing torto",
    descricao: "Quanto mais estranho o pedido, melhor o cartaz.",
    categoria: "formulario",
    tom: "criativo",
    capa: IMG_S3("form.jpg"),
    tema: tema({ fundo: "#0d1b2a", texto: "#e0fbfc", destaque: "#ff6b35", fonte: "serif", alinhamento: "esquerda", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Manda o briefing torto",
        subtitulo: "Quanto mais estranho o pedido, melhor o cartaz.",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "preenchido",
      }),
      form({ titulo: "O recado", destEmail: "studio@email.com", assunto: "Briefing", botao: "Soltar no e-mail" }),
    ],
  }),
  layout({
    id: "formulario-colorido",
    nome: "Escreve aí",
    descricao: "Orçamento, elogio, reclamação, receita de bolo.",
    categoria: "formulario",
    tom: "colorido",
    capa: IMG_S3("form.jpg"),
    tema: tema({ fundo: "#00f5d4", texto: "#111111", destaque: "#f72585", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Escreve aí",
        subtitulo: "Orçamento, elogio, reclamação, receita de bolo.",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "preenchido",
      }),
      form({ titulo: "", botao: "Mandar cor" }),
      icones([
        { nome: "Mail", url: "mailto:oi@email.com", fundo: "#f72585", animacao: "pular" },
        { nome: "MessageCircle", url: "https://wa.me/55", fundo: "#3a0ca3", animacao: "pulso" },
      ]),
    ],
  }),
  layout({
    id: "formulario-sobrio",
    nome: "Correspondência",
    descricao: "Leio tudo. Respondo no dia útil seguinte.",
    categoria: "formulario",
    tom: "sobrio",
    capa: IMG_S3("form.jpg"),
    tema: tema({ fundo: "#e8e4dc", texto: "#2c2926", destaque: "#7a7368", fonte: "serif", alinhamento: "esquerda", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Correspondência",
        subtitulo: "Leio tudo. Respondo no dia útil seguinte.",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "contorno",
      }),
      form({ titulo: "", botao: "Enviar carta" }),
    ],
  }),
  layout({
    id: "formulario-serio",
    nome: "Vale & Associados",
    descricao: "Contencioso societário. Atendimento com hora marcada.",
    categoria: "formulario",
    tom: "serio",
    capa: IMG_S3("form.jpg"),
    tema: tema({ fundo: "#101820", texto: "#f5f2eb", destaque: "#b8956a", alinhamento: "esquerda", largura: "media" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Escritório Vale & Associados",
        subtitulo: "Contencioso societário. Atendimento mediante agendamento.",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "contorno",
      }),
      form({
        titulo: "Pedido de reunião",
        destEmail: "contato@vale.adv.br",
        assunto: "Pedido de reunião",
        botao: "Enviar ao escritório",
      }),
      bloco("texto", { titulo: "", corpo: "Não se trata de plantão. Assuntos urgentes constam no contrato de honorários." }),
    ],
  }),
  layout({
    id: "formulario-minimalista",
    nome: "Escreva",
    descricao: "Só o campo. Só o botão.",
    categoria: "formulario",
    tom: "minimalista",
    capa: "",
    tema: tema({ fundo: "#ffffff", texto: "#0a0a0a", destaque: "#0a0a0a", largura: "estreita" }),
    blocos: () => [
      form({ titulo: "Escreva", botao: "Enviar", mostrarNome: false }),
    ],
  }),
  layout({
    id: "formulario-maximalista",
    nome: "Vamos conversar",
    descricao: "Orçamento, dúvida ou só um oi.",
    categoria: "formulario",
    tom: "maximalista",
    capa: IMG_S3("form.jpg"),
    tema: tema({ fundo: "#fff1f2", texto: "#111111", destaque: "#ff2d55", largura: "media" }),
    blocos: () => [
      bloco("navegacao", { itens: [{ rotulo: "Oi", ancora: "oi" }, { rotulo: "Perguntas", ancora: "faq" }, { rotulo: "Formulário", ancora: "formulario" }] }),
      bloco("secao", { ancora: "oi", titulo: "Vamos conversar", subtitulo: "Orçamento, dúvida ou só um oi." }),
      icones([
        { nome: "Mail", url: "mailto:oi@email.com", fundo: "#ff2d55", animacao: "pulso" },
        { nome: "Phone", url: "https://wa.me/55", fundo: "#111111", animacao: "nenhuma" },
        { nome: "Instagram", url: "https://instagram.com", fundo: "#155eff", animacao: "flutuar" },
      ]),
      bloco("secao", { ancora: "faq", titulo: "Antes de escrever", subtitulo: "" }),
      bloco("texto", { titulo: "Prazo", corpo: "Resposta em horário comercial. Urgente: WhatsApp no botão abaixo." }),
      bloco("texto", { titulo: "Orçamento", corpo: "Manda escopo, data e cidade. Volto com faixa, não com ‘vamos alinhar’." }),
      bloco("texto", { titulo: "Imprensa", corpo: "Press kit no e-mail. Assunto: IMPRENSA + veículo." }),
      botoes([{ rotulo: "WhatsApp", url: "https://wa.me/55", estilo: "contorno" }]),
      bloco("secao", { ancora: "formulario", titulo: "Sua mensagem", subtitulo: "" }),
      form({ titulo: "", botao: "Enviar para meu e-mail" }),
      bloco("redes", { itens: [{ rotulo: "Instagram", url: "https://instagram.com" }, { rotulo: "YouTube", url: "https://youtube.com" }] }),
      bloco("rodape", { texto: "© Estúdio — leio tudo" }),
    ],
  }),
];

const PORTFOLIO = [
  layout({
    id: "portfolio-criativo",
    nome: "Colagem Norte",
    descricao: "Recorte, cola, scan. Trabalho que não cabe no feed.",
    categoria: "portfolio",
    tom: "criativo",
    capa: IMG_S3("portfolio-1.jpg"),
    tema: tema({ fundo: "#2d0a31", texto: "#fff1f2", destaque: "#00f5d4", fonte: "serif", largura: "larga" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Colagem Norte",
        subtitulo: "Recorte, cola, scan. Trabalho que não cabe em feed quadrado.",
        fotoUrl: "",
        cta: "Encomendar série",
        url: "mailto:norte@email.com",
        estiloBotao: "preenchido",
      }),
      galeria(),
      bloco("texto", { titulo: "Em exposição", corpo: "Peças únicas. Clique para ver maior. Troque pelas suas no painel." }),
    ],
  }),
  layout({
    id: "portfolio-colorido",
    nome: "CHOQUE",
    descricao: "Foto de rua. Flash no meio-dia.",
    categoria: "portfolio",
    tom: "colorido",
    capa: IMG_S3("portfolio-2.jpg"),
    tema: tema({ fundo: "#fff700", texto: "#111111", destaque: "#ff006e", largura: "larga" }),
    blocos: () => [
      bloco("capa", {
        titulo: "CHOQUE",
        subtitulo: "Foto de rua. Flash no meio-dia.",
        fotoUrl: "",
        cta: "Comprar print",
        url: "mailto:choque@email.com",
        estiloBotao: "preenchido",
      }),
      galeria(["portfolio-2.jpg", "portfolio-3.jpg", "portfolio-1.jpg", "portfolio-4.jpg"]),
      icones([
        { nome: "Camera", url: "https://instagram.com", fundo: "#ff006e", animacao: "pular" },
        { nome: "ShoppingBag", url: "https://", fundo: "#111111", animacao: "nenhuma" },
      ]),
    ],
  }),
  layout({
    id: "portfolio-sobrio",
    nome: "Sala 4",
    descricao: "Estudos de luz em interiores.",
    categoria: "portfolio",
    tom: "sobrio",
    capa: IMG_S3("portfolio-3.jpg"),
    tema: tema({ fundo: "#f3efe6", texto: "#1f1c19", destaque: "#8a8378", fonte: "serif", largura: "larga" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Sala 4",
        subtitulo: "Estudos de luz em interiores.",
        fotoUrl: "",
        cta: "Visita ao ateliê",
        url: "mailto:sala4@email.com",
        estiloBotao: "texto",
      }),
      galeria(),
    ],
  }),
  layout({
    id: "portfolio-serio",
    nome: "Vale Arquitetura",
    descricao: "Edifícios residenciais. 2014 — hoje.",
    categoria: "portfolio",
    tom: "serio",
    capa: IMG_S3("portfolio-4.jpg"),
    tema: tema({ fundo: "#0a0a0a", texto: "#fafafa", destaque: "#8b7355", fonte: "serif", alinhamento: "esquerda", largura: "larga" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Vale Arquitetura",
        subtitulo: "Edifícios residenciais. 2014 — hoje.",
        fotoUrl: "",
        cta: "Dossiê em PDF",
        url: "mailto:estudio@vale.arq.br",
        estiloBotao: "contorno",
      }),
      galeria(),
      bloco("texto", { titulo: "Seleção", corpo: "Obras entregues. Imagens de obra e ocupação. Briefing sob pedido." }),
    ],
  }),
  layout({
    id: "portfolio-minimalista",
    nome: "Seleção",
    descricao: "Quatro fotos. Quase nenhum texto.",
    categoria: "portfolio",
    tom: "minimalista",
    capa: IMG_S3("portfolio-1.jpg"),
    tema: tema({ fundo: "#ffffff", texto: "#111111", destaque: "#111111", largura: "larga" }),
    blocos: () => [
      galeria(),
      bloco("capa", {
        titulo: "",
        subtitulo: "",
        fotoUrl: "",
        cta: "contato",
        url: "mailto:oi@email.com",
        estiloBotao: "texto",
      }),
    ],
  }),
  layout({
    id: "portfolio-maximalista",
    nome: "Estúdio Norte",
    descricao: "Produto, espaço e quem ocupa o espaço.",
    categoria: "portfolio",
    tom: "maximalista",
    capa: IMG_S3("portfolio-1.jpg"),
    tema: tema({ fundo: "#09090b", texto: "#fafafa", destaque: "#ff4d00", fonte: "serif", largura: "larga" }),
    blocos: () => [
      bloco("navegacao", { itens: [{ rotulo: "Estúdio", ancora: "estudio" }, { rotulo: "Fotos", ancora: "fotos" }, { rotulo: "Clientes", ancora: "clientes" }, { rotulo: "Orçamento", ancora: "orcamento" }] }),
      bloco("secao", { ancora: "estudio", titulo: "", subtitulo: "" }),
      bloco("capa", {
        titulo: "Estúdio Norte",
        subtitulo: "Fotografia de produto, espaço e gente que ocupa o espaço.",
        fotoUrl: "",
        cta: "Pedir orçamento",
        url: "#orcamento",
        estiloBotao: "contorno",
        novaAba: false,
      }),
      icones([
        { nome: "Camera", url: "https://instagram.com", fundo: "#ff4d00", animacao: "pulso" },
        { nome: "Image", url: "https://", fundo: "#155eff", animacao: "nenhuma" },
        { nome: "Mail", url: "mailto:estudio@email.com", fundo: "#424245", animacao: "pulso" },
      ]),
      bloco("secao", { ancora: "fotos", titulo: "Seleção recente", subtitulo: "Clique para ampliar." }),
      galeria(),
      bloco("imagem", { url: IMG_S3("portfolio-2.jpg"), alt: "Destaque", caption: "Série interior, 2026" }),
      bloco("secao", { ancora: "clientes", titulo: "Quem chamou", subtitulo: "" }),
      bloco("depoimentos", {
        itens: [
          { citacao: "Entregaram o ensaio no tom da marca, sem briefing eterno.", autor: "Marca Leste" },
          { citacao: "O espaço parecia maior. E era só luz.", autor: "Hotel Rio" },
        ],
      }),
      bloco("secao", { ancora: "orcamento", titulo: "Orçamento", subtitulo: "Data, cidade e tipo de ensaio." }),
      form({ destEmail: "estudio@email.com", assunto: "Orçamento", botao: "Pedir orçamento" }),
      bloco("rodape", { texto: "© Estúdio Norte" }),
    ],
  }),
];

const LINKS = [
  layout({
    id: "links-criativo",
    nome: "Zeca Comics",
    descricao: "Tira semanal. Um vilão por mês.",
    categoria: "sectioned",
    tom: "criativo",
    capa: IMG_S3("links.jpg"),
    tema: tema({ fundo: "#14001a", texto: "#fdf4ff", destaque: "#c1ff72", fonte: "serif", largura: "estreita" }),
    blocos: () => [
      bloco("navegacao", { itens: [{ rotulo: "Zeca", ancora: "inicio" }, { rotulo: "Gibis", ancora: "links" }, { rotulo: "Oi", ancora: "contato" }] }),
      bloco("secao", { ancora: "inicio", titulo: "", subtitulo: "" }),
      bloco("capa", {
        titulo: "Zeca Comics",
        subtitulo: "Tira semanal. Um vilão por mês.",
        fotoUrl: IMG_S3("links.jpg"),
        cta: "",
        url: "",
        estiloBotao: "preenchido",
      }),
      icones([
        { nome: "BookOpen", url: "https://", fundo: "#c1ff72", cor: "#14001a", animacao: "pular" },
        { nome: "Instagram", url: "https://instagram.com", fundo: "#ff2bd6", animacao: "flutuar" },
      ]),
      bloco("secao", { ancora: "links", titulo: "Gibis", subtitulo: "" }),
      botoes([
        { rotulo: "Capítulo novo", url: "https://", estilo: "preenchido" },
        { rotulo: "Loja de prints", url: "https://", estilo: "contorno" },
        { rotulo: "Patreon", url: "https://", estilo: "texto" },
      ]),
      bloco("secao", { ancora: "contato", titulo: "Manda um vilão", subtitulo: "" }),
      form({ destEmail: "zeca@email.com", assunto: "Vilão", botao: "Enviar" }),
    ],
  }),
  layout({
    id: "links-colorido",
    nome: "DJ Prisma",
    descricao: "Sets, ingressos e o mix da terça.",
    categoria: "sectioned",
    tom: "colorido",
    capa: IMG_S3("links.jpg"),
    tema: tema({ fundo: "#fb5607", texto: "#ffffff", destaque: "#8338ec", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "DJ Prisma",
        subtitulo: "Sets, ingressos e o mix da terça.",
        fotoUrl: IMG_S3("links.jpg"),
        cta: "",
        url: "",
        estiloBotao: "preenchido",
      }),
      icones([
        { nome: "Music", url: "https://spotify.com", fundo: "#8338ec", animacao: "girar" },
        { nome: "Headphones", url: "https://", fundo: "#111111", animacao: "pulso" },
        { nome: "Instagram", url: "https://instagram.com", fundo: "#3a0ca3", animacao: "pular" },
      ]),
      botoes([
        { rotulo: "Próxima festa", url: "https://", estilo: "preenchido" },
        { rotulo: "SoundCloud", url: "https://", estilo: "contorno" },
        { rotulo: "Contratar set", url: "mailto:prisma@email.com", estilo: "contorno" },
      ]),
    ],
  }),
  layout({
    id: "links-sobrio",
    nome: "oficina lenta",
    descricao: "Madeira, faca e tempo.",
    categoria: "sectioned",
    tom: "sobrio",
    capa: IMG_S3("links.jpg"),
    tema: tema({ fundo: "#cfc8bc", texto: "#1f1c19", destaque: "#5c564c", fonte: "serif", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "oficina lenta",
        subtitulo: "Madeira, faca e tempo.",
        fotoUrl: IMG_S3("links.jpg"),
        cta: "",
        url: "",
        estiloBotao: "texto",
      }),
      bloco("texto", { titulo: "", corpo: "Encomendas abertas no primeiro dia útil do mês. O resto é bancada." }),
      botoes([
        { rotulo: "Catálogo", url: "https://", estilo: "contorno" },
        { rotulo: "Lista de espera", url: "mailto:oficina@email.com", estilo: "texto" },
      ]),
    ],
  }),
  layout({
    id: "links-serio",
    nome: "Helena Prado",
    descricao: "Palestras, artigos e imprensa.",
    categoria: "sectioned",
    tom: "serio",
    capa: IMG_S3("links.jpg"),
    tema: tema({ fundo: "#111827", texto: "#f3f4f6", destaque: "#9ca3af", alinhamento: "esquerda", largura: "estreita" }),
    blocos: () => [
      bloco("navegacao", { itens: [{ rotulo: "Perfil", ancora: "inicio" }, { rotulo: "Agenda", ancora: "links" }, { rotulo: "Imprensa", ancora: "contato" }] }),
      bloco("secao", { ancora: "inicio", titulo: "", subtitulo: "" }),
      bloco("capa", {
        titulo: "Helena Prado",
        subtitulo: "Economia e política pública. Palestras e comentário.",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "contorno",
      }),
      bloco("secao", { ancora: "links", titulo: "Agenda", subtitulo: "" }),
      botoes([
        { rotulo: "Palestras 2026", url: "https://", estilo: "preenchido" },
        { rotulo: "Artigos", url: "https://", estilo: "contorno" },
        { rotulo: "LinkedIn", url: "https://linkedin.com", estilo: "texto" },
      ]),
      bloco("secao", { ancora: "contato", titulo: "Imprensa", subtitulo: "" }),
      form({ destEmail: "imprensa@prado.com", assunto: "Imprensa", botao: "Enviar pauta", mostrarMensagem: true }),
    ],
  }),
  layout({
    id: "links-minimalista",
    nome: "Luna",
    descricao: "Ouvir, ver, escrever.",
    categoria: "sectioned",
    tom: "minimalista",
    capa: "",
    tema: tema({ fundo: "#ffffff", texto: "#111111", destaque: "#111111", largura: "estreita" }),
    blocos: () => [
      bloco("capa", {
        titulo: "Luna",
        subtitulo: "",
        fotoUrl: "",
        cta: "",
        url: "",
        estiloBotao: "texto",
      }),
      botoes([
        { rotulo: "Ouvir", url: "https://spotify.com", estilo: "texto" },
        { rotulo: "Ver", url: "https://youtube.com", estilo: "texto" },
        { rotulo: "Escrever", url: "mailto:luna@email.com", estilo: "texto" },
      ]),
    ],
  }),
  layout({
    id: "links-maximalista",
    nome: "Luna Alves",
    descricao: "Música, podcast, newsletter e a loja.",
    categoria: "sectioned",
    tom: "maximalista",
    capa: IMG_S3("links.jpg"),
    tema: tema({ fundo: "#09090b", texto: "#fafafa", destaque: "#b8ff00", largura: "estreita" }),
    blocos: () => [
      bloco("navegacao", {
        itens: [
          { rotulo: "Início", ancora: "inicio" },
          { rotulo: "Sobre", ancora: "sobre" },
          { rotulo: "Links", ancora: "links" },
          { rotulo: "Loja", ancora: "loja" },
          { rotulo: "Contato", ancora: "contato" },
        ],
      }),
      bloco("secao", { ancora: "inicio", titulo: "", subtitulo: "" }),
      bloco("capa", {
        titulo: "Luna Alves",
        subtitulo: "Música, podcast, newsletter e uma loja que não para quieta.",
        fotoUrl: IMG_S3("links.jpg"),
        cta: "",
        url: "",
        estiloBotao: "preenchido",
      }),
      icones([
        { nome: "Youtube", url: "https://youtube.com", fundo: "#155eff", animacao: "pulso" },
        { nome: "Instagram", url: "https://instagram.com", fundo: "#1d1d1f", animacao: "flutuar" },
        { nome: "Music", url: "https://spotify.com", fundo: "#b8ff00", cor: "#111", animacao: "pular" },
        { nome: "Podcast", url: "https://", fundo: "#7c3aed", animacao: "pulso" },
        { nome: "Mail", url: "mailto:luna@email.com", fundo: "#ff2d55", animacao: "nenhuma" },
      ]),
      bloco("secao", { ancora: "sobre", titulo: "Sobre", subtitulo: "O que rola agora." }),
      bloco("texto", { titulo: "", corpo: "Gravo às terças. O resto é ensaio, café e responder quem escreve por aqui." }),
      bloco("texto", { titulo: "Turnê", corpo: "Outubro no sul. Novembro no nordeste. Ingresso no botão da seção Links." }),
      bloco("secao", { ancora: "links", titulo: "Links", subtitulo: "" }),
      botoes([
        { rotulo: "Último episódio", url: "https://youtube.com", estilo: "preenchido" },
        { rotulo: "Newsletter", url: "https://", estilo: "contorno" },
        { rotulo: "Instagram", url: "https://instagram.com", estilo: "contorno" },
        { rotulo: "Spotify", url: "https://spotify.com", estilo: "texto" },
      ]),
      bloco("secao", { ancora: "loja", titulo: "Loja", subtitulo: "Disco, camiseta, zine." }),
      galeria(["portfolio-1.jpg", "portfolio-2.jpg", "portfolio-3.jpg"]),
      botoes([{ rotulo: "Abrir a loja", url: "https://", estilo: "preenchido" }]),
      bloco("secao", { ancora: "contato", titulo: "Contato", subtitulo: "Shows e collab." }),
      form({ destEmail: "luna@email.com", assunto: "Oi, Luna", botao: "Enviar" }),
      bloco("rodape", { texto: "© Luna Alves" }),
    ],
  }),
];

const BRANCOS = [
  layout({
    id: "em-branco-criativo",
    nome: "Página violeta",
    descricao: "Comece do zero neste fundo.",
    categoria: "todos",
    tom: "criativo",
    capa: "",
    tema: tema({ fundo: "#1b0633", texto: "#ffe8ff", destaque: "#ff2bd6", fonte: "serif" }),
    blocos: () => [bloco("capa", { titulo: "Título", subtitulo: "", fotoUrl: "", cta: "", url: "", estiloBotao: "preenchido" })],
  }),
  layout({
    id: "em-branco-colorido",
    nome: "Página amarela",
    descricao: "Comece do zero neste fundo.",
    categoria: "todos",
    tom: "colorido",
    capa: "",
    tema: tema({ fundo: "#ffe600", texto: "#111111", destaque: "#5b21ff" }),
    blocos: () => [bloco("capa", { titulo: "Título", subtitulo: "", fotoUrl: "", cta: "", url: "", estiloBotao: "preenchido" })],
  }),
  layout({
    id: "em-branco-sobrio",
    nome: "Página areia",
    descricao: "Comece do zero neste fundo.",
    categoria: "todos",
    tom: "sobrio",
    capa: "",
    tema: tema({ fundo: "#ebe6dc", texto: "#2f2b26", destaque: "#6f675e", fonte: "serif" }),
    blocos: () => [bloco("capa", { titulo: "Título", subtitulo: "", fotoUrl: "", cta: "", url: "", estiloBotao: "preenchido" })],
  }),
  layout({
    id: "em-branco-serio",
    nome: "Página marinho",
    descricao: "Comece do zero neste fundo.",
    categoria: "todos",
    tom: "serio",
    capa: "",
    tema: tema({ fundo: "#0b1220", texto: "#e8e6e1", destaque: "#c5a572", alinhamento: "esquerda" }),
    blocos: () => [bloco("capa", { titulo: "Título", subtitulo: "", fotoUrl: "", cta: "", url: "", estiloBotao: "preenchido" })],
  }),
  layout({
    id: "em-branco-minimalista",
    nome: "Página branca",
    descricao: "Comece do zero neste fundo.",
    categoria: "todos",
    tom: "minimalista",
    capa: "",
    tema: tema({ fundo: "#ffffff", texto: "#111111", destaque: "#111111", largura: "estreita" }),
    blocos: () => [bloco("capa", { titulo: "Título", subtitulo: "", fotoUrl: "", cta: "", url: "", estiloBotao: "texto" })],
  }),
  layout({
    id: "em-branco-maximalista",
    nome: "Página neon",
    descricao: "Comece do zero neste fundo.",
    categoria: "todos",
    tom: "maximalista",
    capa: "",
    tema: tema({ fundo: "#0b0b10", texto: "#fafafa", destaque: "#ff3b00", largura: "larga" }),
    blocos: () => [bloco("capa", { titulo: "Título", subtitulo: "", fotoUrl: "", cta: "", url: "", estiloBotao: "preenchido" })],
  }),
];

export const LAYOUTS_EXTRA = [...PERFIL, ...LANDING, ...FORMULARIO, ...PORTFOLIO, ...LINKS, ...BRANCOS];
