// Landings com composição própria — inspiradas na variedade do Carrd (#landing),
// sem repetir os modelos antigos (caderno/POP/lista).
import { iconePadrao } from "./icones";

const IMG = (arquivo) =>
  `https://singlepage-bucket-images.s3.us-east-1.amazonaws.com/templates/${arquivo}`;

function dataDaqui(dias) {
  const data = new Date(Date.now() + dias * 86400000);
  data.setMinutes(0, 0, 0);
  const pad = (valor) => String(valor).padStart(2, "0");
  return `${data.getFullYear()}-${pad(data.getMonth() + 1)}-${pad(data.getDate())}T${pad(data.getHours())}:${pad(data.getMinutes())}`;
}

function bloco(tipo, props) {
  return { id: crypto.randomUUID(), tipo, props };
}

function botao(extras = {}) {
  return {
    rotulo: "Meu link",
    url: "https://",
    estilo: "preenchido",
    novaAba: true,
    hoverEscala: 1.04,
    hoverSombra: true,
    ...extras,
  };
}

function celula(filhos) {
  return { id: crypto.randomUUID(), blocos: filhos };
}

function form(extra = {}) {
  return bloco("formulario", {
    destEmail: "oi@email.com",
    assunto: "Lista de espera",
    placeholder: "seu@email.com",
    botao: "Entrar na lista",
    mostrarNome: false,
    mostrarMensagem: false,
    ...extra,
  });
}

export const TEMPLATES_LANDING = [
  {
    id: "landing-northline",
    nome: "Northline",
    descricao: "Split clássico: texto e CTA à esquerda, produto à direita.",
    categoria: "landing",
    tom: "serio",
    plano: "free",
    capa: IMG("landing.jpg"),
    tema: {
      fundo: "#0c1117",
      texto: "#e8eef4",
      destaque: "#6ec3ff",
      fonte: "grotesk",
      alinhamento: "esquerda",
      largura: "media",
      casca: "coluna",
      textura: "nenhuma",
      botao: "suave",
      iconeForma: "simples",
      tituloForma: "pesado",
      tinta: "#e8eef4",
      estilo: "custom-northline",
    },
    blocos: () => [
      bloco("grade", {
        colunas: 2,
        proporcao: "iguais",
        gap: 40,
        celulas: [
          celula([
            bloco("texto", {
              titulo: "Northline",
              tamanhoTitulo: "enorme",
              corpo: "Planejamento financeiro para times de 5 a 50. Um número compartilhado, sem planilha à deriva.",
            }),
            bloco("botoes", {
              layoutId: "linha",
              itens: [
                botao({ rotulo: "Agendar demonstração", url: "#lista", seta: true }),
                botao({ rotulo: "Ver documentação", url: "https://", estilo: "contorno" }),
              ],
            }),
          ]),
          celula([
            bloco("imagem", {
              url: IMG("landing.jpg"),
              alt: "Painel Northline",
              caption: "",
              raio: 16,
            }),
          ]),
        ],
      }),
      bloco("secao", { ancora: "lista", titulo: "", subtitulo: "" }),
      form({ titulo: "Demonstração", assunto: "Demo Northline", botao: "Solicitar horário", mostrarNome: true }),
      bloco("rodape", { texto: "© Northline — finanças para quem fecha o mês junto." }),
    ],
  },

  {
    id: "landing-atlas",
    nome: "Atlas",
    descricao: "Waitlist centrada em cartão — o clássico Carrd de lista de espera.",
    categoria: "landing",
    tom: "serio",
    plano: "free",
    capa: IMG("landing.jpg"),
    tema: {
      fundo: "#e7e5e0",
      texto: "#1c1917",
      destaque: "#1c1917",
      fonte: "sans",
      alinhamento: "centro",
      largura: "estreita",
      casca: "cartao",
      cascaFundo: "#ffffff",
      cascaCor: "#1c1917",
      cascaRaio: 24,
      cascaBorda: "rgba(28,25,23,0.08)",
      cascaSombra: "0 28px 70px rgba(28,25,23,0.12)",
      textura: "nenhuma",
      botao: "pilula",
      iconeForma: "circulo",
      tituloForma: "pesado",
      tinta: "#1c1917",
      estilo: "custom-atlas",
    },
    blocos: () => [
      bloco("icones", {
        layoutId: "centro",
        itens: [
          iconePadrao({ nome: "Navigation", url: "", fundo: "#1c1917", cor: "#fff", animacao: "nenhuma" }),
        ],
      }),
      bloco("capa", {
        layoutId: "centro",
        titulo: "Atlas chega em outubro",
        subtitulo: "Mapas operacionais para times remotos. Um lugar para o que importa — o resto fica de fora.",
        fotoUrl: "",
        cta: "",
        url: "",
      }),
      form({ titulo: "", assunto: "Lista Atlas", botao: "Quero o convite" }),
      bloco("texto", {
        titulo: "",
        corpo: "Já são 2.400 pessoas na fila. Sem spam — só o e-mail do lançamento.",
        tamanhoTexto: "pequeno",
      }),
    ],
  },

  {
    id: "landing-field",
    nome: "Field Notes",
    descricao: "Editorial serifado: foto, manifesto e três colunas de prova.",
    categoria: "landing",
    tom: "editorial",
    plano: "pro",
    capa: IMG("portfolio-1.jpg"),
    tema: {
      fundo: "#f4f0e8",
      texto: "#1a1714",
      destaque: "#8a5a2b",
      fonte: "editorial",
      alinhamento: "centro",
      largura: "media",
      casca: "moldura",
      cascaBorda: "rgba(26,23,20,0.22)",
      textura: "nenhuma",
      botao: "linha",
      iconeForma: "simples",
      tituloForma: "caps",
      tinta: "#1a1714",
      estilo: "custom-field",
    },
    blocos: () => [
      bloco("imagem", {
        url: IMG("portfolio-1.jpg"),
        alt: "Caderno Field Notes",
        caption: "Edição 04 — papel creme, 160 páginas",
        raio: 0,
      }),
      bloco("capa", {
        titulo: "Field Notes",
        subtitulo: "Um caderno para quem ainda escreve à mão. Sem app. Sem nuvem. Só o que cabe na mesa.",
        fotoUrl: "",
        cta: "Reservar a edição",
        url: "#reserva",
        estiloBotao: "texto",
        novaAba: false,
      }),
      bloco("grade", {
        colunas: 3,
        gap: 20,
        celulas: [
          celula([bloco("texto", { titulo: "Papel", corpo: "120 g/m², creme, pensado para caneta e lápis." })]),
          celula([bloco("texto", { titulo: "Formato", corpo: "A5. Cabe na bolsa sem virar bloco de anotações de reunião." })]),
          celula([bloco("texto", { titulo: "Tiragem", corpo: "1.200 unidades. Depois disso, a capa muda." })]),
        ],
      }),
      bloco("secao", { ancora: "reserva", titulo: "Lista da edição 04", subtitulo: "" }),
      form({ titulo: "", assunto: "Field Notes 04", botao: "Avisar-me", mostrarNome: false }),
    ],
  },

  {
    id: "landing-summit",
    nome: "Summit",
    descricao: "Evento com contagem regressiva, data e inscrição.",
    categoria: "landing",
    tom: "serio",
    plano: "ultra",
    capa: IMG("landing.jpg"),
    tema: {
      fundoModo: "degrade",
      fundoDe: "#06080c",
      fundoPara: "#152033",
      fundoAngulo: 160,
      texto: "#f2f5f9",
      destaque: "#f0c36a",
      fonte: "display",
      alinhamento: "centro",
      largura: "media",
      casca: "coluna",
      textura: "brilho",
      botao: "suave",
      iconeForma: "circulo",
      tituloForma: "display",
      tinta: "#f2f5f9",
      estilo: "custom-summit",
    },
    blocos: () => [
      bloco("texto", {
        titulo: "Summit São Paulo",
        tamanhoTitulo: "enorme",
        corpo: "Um dia fechado para founders e operadores. Sem painéis genéricos — só conversas com quem já passou pelo buraco.",
      }),
      bloco("contador", {
        layoutId: "caixas",
        titulo: "Abertura em",
        alvo: dataDaqui(21),
        mostrarSegundos: false,
        textoFim: "As portas abriram.",
        corCaixa: "rgba(240,195,106,0.12)",
      }),
      bloco("texto", {
        titulo: "",
        corpo: "12 de novembro · Teatro Unimed · 9h às 18h",
        tamanhoTexto: "medio",
      }),
      form({
        titulo: "Inscrição",
        assunto: "Summit SP",
        botao: "Garantir lugar",
        mostrarNome: true,
      }),
      bloco("rodape", { texto: "Vagas limitadas. Confirmação por e-mail em até 48h." }),
    ],
  },

  {
    id: "landing-meridian",
    nome: "Meridian",
    descricao: "Minimalista tipo Apple: título enorme, uma frase, um botão.",
    categoria: "landing",
    tom: "minimalista",
    plano: "free",
    capa: "",
    tema: {
      fundo: "#f5f5f7",
      texto: "#1d1d1f",
      destaque: "#0071e3",
      fonte: "sans",
      alinhamento: "centro",
      largura: "estreita",
      casca: "coluna",
      textura: "nenhuma",
      botao: "pilula",
      iconeForma: "simples",
      tituloForma: "leve",
      tinta: "#1d1d1f",
      estilo: "custom-meridian",
    },
    blocos: () => [
      bloco("capa", {
        layoutId: "centro",
        titulo: "Meridian",
        tamanhoTitulo: "enorme",
        subtitulo: "O calendário que mostra só o que cabe no dia. O resto espera.",
        fotoUrl: "",
        cta: "Baixar para Mac",
        url: "https://",
        estiloBotao: "preenchido",
      }),
      bloco("botoes", {
        layoutId: "linha",
        itens: [
          botao({ rotulo: "Windows", url: "https://", estilo: "texto" }),
          botao({ rotulo: "Notas de versão", url: "https://", estilo: "texto" }),
        ],
      }),
    ],
  },

  {
    id: "landing-harbor",
    nome: "Harbor",
    descricao: "Foto full-bleed com conteúdo em vidro por cima — produto no ar.",
    categoria: "landing",
    tom: "foto",
    plano: "pro",
    capa: IMG("landing.jpg"),
    tema: {
      fundoModo: "degrade",
      fundoDe: "#1a2330",
      fundoPara: "#4a5568",
      fundoAngulo: 180,
      texto: "#ffffff",
      destaque: "#ffffff",
      fonte: "sans",
      alinhamento: "centro",
      largura: "estreita",
      casca: "cheia",
      textura: "nenhuma",
      botao: "vidro",
      iconeForma: "vidro",
      tituloForma: "pesado",
      tinta: "#ffffff",
      estilo: "custom-harbor",
    },
    blocos: () => [
      bloco("capa", {
        layoutId: "fullbleed",
        titulo: "Harbor",
        subtitulo: "Reserva de estúdios e salas para criativos. Sem intermediário, sem taxa escondida.",
        fotoUrl: IMG("landing.jpg"),
        cta: "Ver disponibilidade",
        url: "#form",
        estiloBotao: "contorno",
        minAltura: 520,
        raio: 0,
        paddingCima: 64,
        paddingBaixo: 48,
        paddingLados: 28,
        novaAba: false,
      }),
      bloco("secao", { ancora: "form", titulo: "", subtitulo: "" }),
      form({
        titulo: "Pedidos de visita",
        assunto: "Harbor visita",
        botao: "Agendar",
        mostrarNome: true,
        mostrarMensagem: true,
      }),
    ],
  },

  {
    id: "landing-ledger",
    nome: "Ledger",
    descricao: "SaaS B2B: recursos em cards, prova social e formulário.",
    categoria: "landing",
    tom: "serio",
    plano: "pro",
    capa: IMG("landing.jpg"),
    tema: {
      fundo: "#f7f8fa",
      texto: "#12141a",
      destaque: "#1a4fd6",
      fonte: "moderna",
      alinhamento: "esquerda",
      largura: "media",
      casca: "coluna",
      textura: "nenhuma",
      botao: "suave",
      iconeForma: "quadrado",
      tituloForma: "pesado",
      tinta: "#12141a",
      estilo: "custom-ledger",
    },
    blocos: () => [
      bloco("navegacao", {
        itens: [
          { rotulo: "Produto", ancora: "produto" },
          { rotulo: "Prova", ancora: "prova" },
          { rotulo: "Contato", ancora: "contato" },
        ],
      }),
      bloco("secao", { ancora: "produto", titulo: "", subtitulo: "" }),
      bloco("capa", {
        layoutId: "esquerda",
        titulo: "Caixa claro para sócios que ainda fecham em planilha",
        subtitulo: "Saldo, previsão de 30 dias e um relatório que o conselho lê sem tradução.",
        fotoUrl: "",
        cta: "Pedir demonstração",
        url: "#contato",
        estiloBotao: "preenchido",
        novaAba: false,
      }),
      bloco("cartoes", {
        layoutId: "grade",
        colunas: 3,
        itens: [
          { icone: "Wallet", titulo: "Um número", corpo: "Saldo consolidado. Sem abas. Sem versão ‘final_v3’." },
          { icone: "Calendar", titulo: "30 dias à frente", corpo: "Previsão simples: o que entra, o que sai, o que falta." },
          { icone: "FileText", titulo: "Relatório curto", corpo: "PDF de uma página. Pronto para enviar ao conselho." },
        ],
      }),
      bloco("secao", { ancora: "prova", titulo: "Quem já fecha com Ledger", subtitulo: "" }),
      bloco("depoimentos", {
        layoutId: "grade",
        itens: [
          { citacao: "Paramos de brigar por abas. O fechamento virou ritual de meia hora.", autor: "Marina · COO", fotoUrl: "" },
          { citacao: "O relatório de uma página é o que o board finalmente lê.", autor: "Paulo · CFO", fotoUrl: "" },
        ],
      }),
      bloco("secao", { ancora: "contato", titulo: "Demonstração", subtitulo: "Resposta em até um dia útil." }),
      form({ titulo: "", assunto: "Demo Ledger", botao: "Solicitar", mostrarNome: true }),
    ],
  },

  {
    id: "landing-pulse",
    nome: "Pulse",
    descricao: "App: navegação, hero, benefícios e botões de loja.",
    categoria: "landing",
    tom: "produto",
    plano: "pro",
    capa: IMG("landing.jpg"),
    tema: {
      fundo: "#0a0a0b",
      texto: "#f4f4f5",
      destaque: "#34d399",
      fonte: "moderna",
      alinhamento: "centro",
      largura: "media",
      casca: "coluna",
      textura: "nenhuma",
      botao: "pilula",
      iconeForma: "circulo",
      tituloForma: "pesado",
      tinta: "#f4f4f5",
      estilo: "custom-pulse",
    },
    blocos: () => [
      bloco("navegacao", {
        itens: [
          { rotulo: "Recursos", ancora: "recursos" },
          { rotulo: "Baixar", ancora: "baixar" },
        ],
      }),
      bloco("capa", {
        titulo: "Pulse",
        subtitulo: "Hábitos sem ranking. Um check por dia, lembrete gentil, zero streak tóxico.",
        fotoUrl: "",
        cta: "",
        url: "",
      }),
      bloco("imagem", {
        url: IMG("landing.jpg"),
        alt: "App Pulse",
        caption: "",
        raio: 20,
      }),
      bloco("secao", { ancora: "recursos", titulo: "", subtitulo: "" }),
      bloco("cartoes", {
        layoutId: "grade",
        colunas: 3,
        itens: [
          { icone: "Bell", titulo: "Lembrete", corpo: "Um aviso. Só no horário que você escolheu." },
          { icone: "Moon", titulo: "Modo noite", corpo: "A tela some depois das 22h. O app também descansa." },
          { icone: "Lock", titulo: "Privado", corpo: "Sem feed. Sem compartilhar. Sem comparação." },
        ],
      }),
      bloco("secao", { ancora: "baixar", titulo: "Baixar", subtitulo: "" }),
      bloco("botoes", {
        layoutId: "linha",
        itens: [
          botao({ rotulo: "App Store", url: "https://", icone: "Download", seta: true }),
          botao({ rotulo: "Google Play", url: "https://", estilo: "contorno", icone: "Play" }),
        ],
      }),
    ],
  },

  {
    id: "landing-vellum",
    nome: "Vellum",
    descricao: "Faixas alternadas — curso/produto em seções com personalidade.",
    categoria: "landing",
    tom: "editorial",
    plano: "pro",
    capa: IMG("portfolio-2.jpg"),
    tema: {
      fundo: "#faf7f2",
      texto: "#1b1b1b",
      destaque: "#1b1b1b",
      fonte: "display",
      alinhamento: "esquerda",
      largura: "media",
      casca: "coluna",
      textura: "ruido",
      botao: "bloco",
      iconeForma: "simples",
      tituloForma: "display",
      tinta: "#1b1b1b",
      estilo: "custom-vellum",
    },
    blocos: () => [
      bloco("capa", {
        titulo: "Vellum",
        tamanhoTitulo: "enorme",
        subtitulo: "Um curso de tipografia aplicada. Quatro aulas. Trabalho final revisado.",
        fotoUrl: "",
        cta: "Quero a próxima turma",
        url: "#turma",
        estiloBotao: "preenchido",
        novaAba: false,
      }),
      bloco("faixa", {
        layoutId: "esquerda",
        fundo: "#1b1b1b",
        texto: "#faf7f2",
        titulo: "O que você leva",
        subtitulo: "",
        padding: "largo",
        blocos: [
          bloco("texto", {
            titulo: "",
            corpo: "Critério tipográfico para marca, editorial e embalagem. Não é software — é olhar.",
          }),
          bloco("cartoes", {
            layoutId: "lista",
            colunas: 1,
            itens: [
              { titulo: "Aula 1 — Hierarquia", corpo: "O que o olho lê primeiro, e por quê." },
              { titulo: "Aula 2 — Pares", corpo: "Serifa e sem serifa sem briga na página." },
              { titulo: "Aula 3 — Espaço", corpo: "Entrelinha, margem e o silêncio que vende." },
              { titulo: "Aula 4 — Entrega", corpo: "Revisão ao vivo do seu projeto." },
            ],
          }),
        ],
      }),
      bloco("faixa", {
        layoutId: "esquerda",
        fundo: "#e8e0d4",
        texto: "#1b1b1b",
        titulo: "Próxima turma",
        subtitulo: "Março · online · 16 vagas",
        padding: "medio",
        blocos: [
          bloco("secao", { ancora: "turma", titulo: "", subtitulo: "" }),
          form({ titulo: "", assunto: "Turma Vellum", botao: "Reservar vaga", mostrarNome: true }),
        ],
      }),
    ],
  },

  {
    id: "landing-signal",
    nome: "Signal",
    descricao: "Manifesto brutalista: tipografia dura, prova em cards e CTA seco.",
    categoria: "landing",
    tom: "brutal",
    plano: "ultra",
    capa: IMG("links.jpg"),
    tema: {
      fundo: "#111111",
      texto: "#f5f5f5",
      destaque: "#ffe14a",
      fonte: "poster",
      alinhamento: "esquerda",
      largura: "media",
      casca: "coluna",
      textura: "grade",
      botao: "chip",
      botaoCor: "#ffe14a",
      iconeForma: "quadrado",
      tituloForma: "caps",
      tinta: "#f5f5f5",
      estilo: "custom-signal",
    },
    blocos: () => [
      bloco("capa", {
        layoutId: "esquerda",
        titulo: "Signal não vende atenção. Vende clareza.",
        subtitulo: "Consultoria de posicionamento para marcas que já falam demais e ainda não disseram nada.",
        fotoUrl: "",
        cta: "",
        url: "",
      }),
      bloco("botoes", {
        layoutId: "cartoes",
        itens: [
          botao({
            rotulo: "Diagnóstico",
            subtitulo: "Duas semanas. Um documento. Uma decisão.",
            url: "#contato",
            fundo: "#ffe14a",
            cor: "#111",
            borda: "#ffe14a",
            sombraDura: "4px 4px 0 #ffe14a",
            raio: 0,
            seta: true,
            novaAba: false,
          }),
          botao({
            rotulo: "Casos",
            subtitulo: "Antes e depois — só o que pode ser mostrado.",
            url: "https://",
            fundo: "#222",
            cor: "#f5f5f5",
            borda: "#f5f5f5",
            bordaLargura: 2,
            sombraDura: "4px 4px 0 #f5f5f5",
            raio: 0,
            seta: true,
          }),
        ],
      }),
      bloco("secao", { ancora: "contato", titulo: "Fale com a gente", subtitulo: "" }),
      form({
        titulo: "",
        assunto: "Signal",
        botao: "Enviar brief",
        mostrarNome: true,
        mostrarMensagem: true,
      }),
      bloco("rodape", { texto: "© Signal — clareza sob contrato." }),
    ],
  },
];
